name: Generate Snake Animation

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch: # Allow manual triggering

  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  generate:
    permissions:
      contents: write # Allow writing to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Set a timeout for the job

    steps:
      # Step 1: Generate the snake.svg file
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nero213 # Replace with your GitHub username
          outputs: dist/snake.svg?palette=github-dark # Output file and theme

      # Step 2: Push the snake.svg file to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Branch where the file will be pushed
          build_dir: dist # Directory containing the generated file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
